//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transfer_centre.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class transfer
    {
        public int ID { get; set; }

        [Required]
        [StringLength(60,MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [Range(0, 100)]
        public int age { get; set; }
        [Required]
        public string transferred_from { get; set; }
        [Required]
        public string transferred_to { get; set; }
        [Required]
        public string value { get; set; }

        public string image { get; set; }

        public Nullable<int> Likes { get; set; }
        public Nullable<int> Dislikes { get; set; }
    }
}
